# Generated by Django 4.1.7 on 2023-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("EG", "Eggs"),
                    ("EQP", "Equipment"),
                    ("LV", "LiveStock"),
                    ("Cl", "Course"),
                    ("FP", "Frozen_products"),
                    ("CF", "Chicken Food"),
                ],
                max_length=3,
            ),
        ),
    ]
