# Generated by Django 4.1.7 on 2023-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("ec", "Eastern Cape"),
                    ("ec", "Free State"),
                    ("ec", "Gauteng"),
                    ("ec", "KwaZulu-Natal"),
                    ("ec", "Limpopo"),
                    ("ec", "Mpumalanga"),
                    ("ec", "Northern Cape"),
                    ("ec", "North West"),
                    ("ec", "Western Cape"),
                ],
                default="",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="customer", name="zipcode", field=models.IntegerField(default=0),
        ),
    ]
